# SPDX-License-Identifier: MIT

name: NN6000-DAEDE

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: 'Additional package config lines, one per line.'
        required: false
        type: string
      TEST:
        description: 'Only generate the final config without compiling firmware.'
        default: false
        required: false
        type: boolean

permissions: write-all

jobs:
  build:
    name: NN6000 v2
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: NN6000-DAEDE
      WRT_THEME: aurora
      WRT_NAME: OWRT-NN6000
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.100.1
      WRT_PW: none
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: main
      WRT_SOURCE: VIKINGYFY/immortalwrt
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
